### ISSUE TITLE
Can't download Book

### ISSUE THREAD

**Issue by outrun0506** [laurensk/digi4school-pdf#3]
Hey Thanks for providing this Script.

If we try to download a book, we get following Error:

```
(node:11960) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Function.<anonymous> (c:\Users\thoma\Downloads\digi4school\dist\D4SBookProperties.js:49:53)
    at Generator.next (<anonymous>)
    at c:\Users\thoma\Downloads\digi4school\dist\D4SBookProperties.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\thoma\Downloads\digi4school\dist\D4SBookProperties.js:4:12)
    at Request._callback (c:\Users\thoma\Downloads\digi4school\dist\D4SBookProperties.js:27:26)
    at Request.self.callback (c:\Users\thoma\Downloads\digi4school\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (c:\Users\thoma\Downloads\digi4school\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any Hints?

**Comment by laurensk** [comment]
Hey @outrun0506! Could it be that you have tried to download an open book? These are the books which are currently to read on digi4school. Open books are not supported to download.

Let me know if that was the problem! If it's still not working, please comment again on this issue.

**Comment by outrun0506** [comment]
Well, no we were login and tried with the same Account

**Comment by outrun0506** [comment]
Well, no we closed all Browser Tabs before
