### ISSUE TITLE
Download of book failed

### ISSUE THREAD

**Issue by vierzwerge** [laurensk/digi4school-pdf#4]
Hi,
many thanks for this great script.

But for some books we got the following error (other books are ok):

`(node:31643) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Function.<anonymous> (/home/xxxx/digi4school-pdf/dist/D4SAuthHelper.js:63:33)
    at Generator.next (<anonymous>)
    at /home/xxxx/digi4school-pdf/dist/D4SAuthHelper.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/xxxx/digi4school-pdf/dist/D4SAuthHelper.js:4:12)
    at Request._callback (/home/xxxx/digi4school-pdf/dist/D4SAuthHelper.js:59:38)
    at Request.self.callback (/home/xxxx/digi4school-pdf/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/xxxx/digi4school-pdf/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
(node:31643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31643) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Thank you

**Comment by vierzwerge** [comment]
Hi,
I checked this one more and the books not working are open books and these books are currently not supported to be downloaded, is this right ?
Thank you

**Comment by laurensk** [comment]
Hi @vierzwerge,
Correct, open books are and will never be supported by this script. This is mainly due to the fact, that only books you bought should be downloadable.

**Comment by vierzwerge** [comment]
Hi @laurensk , ok, I understand. 
Many thanks.
vierzwerge
